test_square (__main__.TestExercice) ... ERROR
test_square_root (__main__.TestExercice) ... ok

======================================================================
ERROR: test_square (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 17, in test_square
    output_exo = list(map(exercice.square, self.numbers))
  File "/home/runner/work/c01_ch3_exercice1-JeremCV/c01_ch3_exercice1-JeremCV/exercice.py", line 12, in square
    return squared
NameError: name 'squared' is not defined

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (errors=1)
